In [7]:
import pandas as pd
import numpy as np

In [12]:
df_full = pd.read_csv("data/OLD/Data_with_coding(full).csv")
df_full.head()

,CONCERNCO_W49_num,BENEFITCO_W49_num,POSNEGCO_W49_num,TRACKCO1a_W49_num,TRACKCO1b_W49_num,CONTROLCO_W49_num,UNDERSTANDCO_W49_num,ANONYMOUS1CO_W49_num,CONCERNGOV_W49_num,BENEFITGOV_W49_num,POSNEGGOV_W49_num,TRACKGOV1a_W49_num,TRACKGOV1b_W49_num,CONTROLGOV_W49_num,UNDERSTANDGOV_W49_num,ANONYMOUS1GOV_W49_num
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
1,3.0,0.0,0.0,2.0,0.0,3.0,1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.0,0.0,0.0,2.0,1.0,1.0,1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,4.0,4.0,0.0,1.0,0.0
4,4.0,NaN,0.0,4.0,4.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
# Load file
df = pd.read_csv("data/Overview_questions.csv")

# Define your target prefixes
targets = [
    "TRACKGOV1a", "TRACKGOV1b", "CONCERNGOV", "BENEFITGOV",
    "CONTROLGOV", "UNDERSTANDGOV", "POSNEGGOV", "ANONYMOUS1GOV",
    "CONCERNGRPd","CONCERNGRPf", "PP5", "PP6", "SHARE1", "PROFILE1"
]

# Keep rows where the 'ID' contains one of these substrings
mask = df["ID"].apply(lambda x: any(t in str(x) for t in targets))
subset = df[mask]
subset.head(26)

,ID,Category,Question,All Options,Option_1,Option_2,Option_3,Option_4,Coding_Scheme
31,TRACKGOV1a_W49,Public Surveillance - Perceptions,"As far as you know, how much of what you do ON...",See questionnaire (multiple options),None of it,All or almost all of it,Most of it,Some of it,"{'None of it': 0, 'Some of it': 1, 'Most of it..."
32,TRACKGOV1b_W49,Public Surveillance - Perceptions,"As far as you know, how much of what you do OF...",See questionnaire (multiple options),None of it,All or almost all of it,Very little of it,Some of it,"{'None of it': 0, 'Very little of it': 1, 'Som..."
33,CONCERNGOV_W49,Public Surveillance - Attitudes,"How concerned are you, if at all, about how th...",1 Very concerned | 2 Somewhat concerned | 3 No...,Not too concerned,Not at all concerned,Somewhat concerned,Very concerned,"{'Not at all concerned': 0, 'Not too concerned..."
34,BENEFITGOV_W49,Public Surveillance - Attitudes,How much do you feel you personally benefit fr...,1 A great deal | 2 Some | 3 Very little | 4 None,Very little,Some,A great deal,Refused,"{'Very little': 0, 'Some': 1, 'A great deal': ..."
35,CONTROLGOV_W49,Public Surveillance - Perceptions,How much control do you think you have over th...,1 A great deal | 2 Some | 3 Very little | 4 None,No control,Very little control,Some control,Refused,"{'No control': 0, 'Very little control': 1, 'S..."
36,UNDERSTANDGOV_W49,Public Surveillance - Perceptions,How much do you feel you understand what the g...,1 A great deal | 2 Some | 3 Very little | 4 No...,Nothing,Very little,Some,A great deal,"{'Nothing': 0, 'Very little': 1, 'Some': 2, 'A..."
37,POSNEGGOV_W49,Public Surveillance - Attitudes,"On balance, which would you say most accuratel...",1 Benefits outweigh risks | 2 Risks outweigh b...,The potential risks of the government collecti...,The benefits the government can provide by col...,Refused,NaN,{'The potential risks of the government collec...
38,ANONYMOUS1GOV_W49,Public Surveillance - Attitudes,Do you think it is possible to go about daily ...,1 Yes | 2 No,"Yes, it is possible","No, it is not possible",Refused,NaN,"{'No, it is not possible': 0, 'Yes, it is poss..."
42,CONCERNGRPd_W49,Group-specific Concerns,How concerned are you about the companies you ...,1 Very concerned | 2 Somewhat concerned | 3 No...,Not concerned,Concerned a little,Concerned a lot,Refused,"{'Not concerned': 0, 'Concerned a little': 1, ..."
44,CONCERNGRPf_W49,Group-specific Concerns,How concerned are you about the social media s...,1 Very concerned | 2 Somewhat concerned | 3 No...,Concerned a lot,Concerned a little,Not concerned,Refused,"{'Not concerned': 0, 'Concerned a little': 1, ..."
55,PP5a_W49,Privacy Policies & Regulation,How confident are you that companies follow th...,1 Very confident | 2 Somewhat confident | 3 No...,Somewhat confident,Not too confident,Not confident at all,Very confident,"{'Not confident at all': 0, 'Not too confident..."
56,PP5b_W49,Privacy Policies & Regulation,How confident are you that companies promptly ...,1 Very confident | 2 Somewhat confident | 3 No...,Somewhat confident,Not too confident,Not confident at all,Very confident,"{'Not confident at all': 0, 'Not too confident..."
57,PP5c_W49,Privacy Policies & Regulation,How confident are you that companies publicly ...,1 Very confident | 2 Somewhat confident | 3 No...,Somewhat confident,Not confident at all,Not too confident,Very confident,"{'Not confident at all': 0, 'Not too confident..."
58,PP5d_W49,Privacy Policies & Regulation,How confident are you that companies use your ...,1 Very confident | 2 Somewhat confident | 3 No...,Somewhat confident,Not confident at all,Not too confident,Refused,"{'Not confident at all': 0, 'Not too confident..."
59,PP5e_W49,Privacy Policies & Regulation,How confident are you that companies will be h...,1 Very confident | 2 Somewhat confident | 3 No...,Somewhat confident,Not confident at all,Not too confident,Very confident,"{'Not confident at all': 0, 'Not too confident..."
60,PP6a_W49,Privacy Policies & Regulation,How comfortable are you with companies using y...,1 Very comfortable | 2 Somewhat comfortable | ...,Somewhat comfortable,Not too comfortable,Not comfortable at all,Very comfortable,"{'Not comfortable at all': 0, 'Not too comfort..."
61,PP6b_W49,Privacy Policies & Regulation,How comfortable are you with companies sharing...,1 Very comfortable | 2 Somewhat comfortable | ...,Somewhat comfortable,Not too comfortable,Not comfortable at all,Very comfortable,"{'Not comfortable at all': 0, 'Not too comfort..."
62,PP6c_W49,Privacy Policies & Regulation,How comfortable are you with companies using y...,1 Very comfortable | 2 Somewhat comfortable | ...,Somewhat comfortable,Not too comfortable,Not comfortable at all,Very comfortable,"{'Not comfortable at all': 0, 'Not too comfort..."
66,SHARE1_W49,Privacy Policies & Regulation,Have you recently decided NOT to use a product...,See questionnaire (multiple options),"No, have not done this","Yes, have done this",Refused,NaN,"{'No, have not done this': 0, 'Yes, have done ..."
91,PROFILE1_W49,Data Rights & Profiling,"Prior to today, how much had you heard or read...",See questionnaire (multiple options),Nothing at all,A little,A lot,Refused,"{'Nothing at all': 0, 'A little': 1, 'A lot': ..."

In [11]:
mask = df_full["ID"].apply(lambda x: any(t in str(x) for t in targets))
data_subset = df_full[mask]

KeyError: 'ID'